version: 2
jobs:
  install:
    docker:
      - image: circleci/node:8.9.4
    working_directory: ~/ci-test
    steps:
      - checkout
      - run: yarn install
      - save_cache:
          paths:
            - node_modules/
          key: dependency-cache-{{ checksum "package.json" }}
  build:
    docker:
      - image: circleci/node:8.9.4
    working_directory: ~/ci-test
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run: yarn run build
      - save_cache:
          paths:
            - node_modules/
            - build/
          key: build-cache-{{ .BuildNum }}
  test:
    docker:
      - image: circleci/node:8.9.4
    working_directory: ~/ci-test
    steps:
      - checkout
      - restore_cache:
          key: build-cache-{{ .BuildNum }}
      - run: yarn test
      - store_artifacts:
          path: tests/coverage/
      # duplicate of store_artifacts because circle 2.0 doesn't seem to support this option fully yet for html coverage
      - store_test_results:
          path: tests/coverage/
  lint:
    docker:
      - image: circleci/node:8.9.4
    working_directory: ~/ci-test
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run: yarn run lint --debug-check --list-different
workflows:
  version: 2
  build-test-lint:
    jobs:
      - install
      - build:
        	requires:
          	- install
      - lint:
        	requires:
          	- install
      - test:
        	requires:
          	- build
