version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.9.4
    working_directory: ~/ci-test
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install dependencies
          command: yarn install
      - save_cache:
          paths:
            - node_modules/
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Build lib
          command: yarn run build
      - run:
          name: Test lib
          command: yarn test
      - store_artifacts:
          path: tests/coverage/
      # duplicate of store_artifacts because circle 2.0 doesn't seem to support this option fully yet for html coverage
      - store_test_results:
          path: tests/coverage/
      - run:
          name: Lint src
          command: yarn run lint --debug-check --list-different
